### ISSUE TITLE
gi import Error (Currently no cross-platform support)

### ISSUE THREAD

**Issue by joaochris** [RMichaelSwan/tele-capture#1]
Traceback (most recent call last):
  File "C:\Scripts\capture.py", line 14, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'

**Comment by RMichaelSwan** [comment]
This only works if you have GTK 3.0 installed and your OS uses GTK for GUIs. I've only tested on Ubuntu 18.04 so far. You can try using this library to make it work inside a virtual environment possibly: https://pypi.org/project/vext.gi

In order to work on Windows [seamlessly] you will likely have to make use of the win32 API--it's not my focus right now, but if someone wants to make a windows (or Mac) version of the WindowCapture class, I can definitely include it. Possible Windows solution: https://stackoverflow.com/a/3586280/5715374

A cross platform solution would be to use MSS to capture the entire screen and work from there, but that wouldn't work if your window becomes covered up and might result in a lower framerate: https://python-mss.readthedocs.io/examples.html#opencv-numpy .

Also, once I get audio capture working, that likely won't be cross-platform either, so that's another issue.
